### ISSUE TITLE
[DOCS] Wrappers documentation needs an update

### ISSUE THREAD

**Issue by wilhadams** [theochem/gbasis#116]
When #106 was pulled in, I didn't notice that we should update the notes.pdf file as well, because the wrappers return both the `basis` and, newly, `coord_types`. I'll try to update the docs soon.

**Comment by maximilianvz** [comment]
Apparently, in order to be assigned to issues in this repository, I need to leave a comment somewhere. This is the point of this comment.

**Comment by gabrielasd** [comment]
Hi @leila-pujal, just to make sure, the notes under the [docs](https://github.com/theochem/gbasis/tree/master/docs) folder are the latest version?

**Comment by leila-pujal** [comment]
Hi @gabrielasd, yes those notes are the latest. But now I was thinking @maximilianvz is working on issue #113 and basically the newly added `coord_typ` variable that was returned we are planning to incorporate that as an attribute of the `GeneralizedContractionShell` class. I think you can start updating the notes incorporating all the modifications coming from IOData incorporated in PR #106 except the `coord_type` . There should be a draft for issue #113 soon so then you can update the notes based on that.  Let me know what you think.

**Comment by gabrielasd** [comment]
OK! Yes, that makes sense. thanks @leila-pujal

**Comment by PaulWAyers** [comment]
There are also (more scientific, less technical) notes in the Discussion thread in case that is helpful.
https://github.com/orgs/theochem/discussions/2

**Comment by gabrielasd** [comment]
> There are also (more scientific, less technical) notes in the Discussion thread in case that is helpful. https://github.com/orgs/theochem/discussions/2

@PaulWAyers I could not access this link. I can get to theochem, but I don't see the discussion board there.

**Comment by gabrielasd** [comment]
@leila-pujal 
For the docstrings in the wrappers module, I've done a 1st read and update in my fork of the project. They were minor changes in the `from_iodata` function. I left out any modifications dealing with the `coord_type` variable like we talked and I've seen that @maximilianvz already updated this part within his PR.
For the update in the latex notes, I've only been looking at section 4 "Basis Set" since it seemed to me the most related to this issue. However, should I check other sections too?

Also, should I include the examples for how to use `from_iodata` and `from_pyscf` from the notes as part of the wrappers docstrings?
