### ISSUE TITLE
[REQUEST] Supporting alternative orders for spherical orbitals

### ISSUE THREAD

**Issue by Ali-Tehrani** [theochem/gbasis#122]
**Is your feature request related to a problem? Please describe.**

I would like a way of specifying the spherical order when evaluating basis-functions or integrals.

 For example, IOData specifies the order for D-type orbitals as : ['c0', 'c1', 's1', 'c2', 's2'], whereas PySCF would be ["s2", "s1", "c0", "c1", "c2"].  Similarly for F-type orbitals, IOData does ["s3", "s2", "s1", "c0", "c1", "c2", "c3"] and PySCF is ['c0', 'c1', 's1', 'c2', 's2', 'c3', 's3'], where "c" are cosine-type functions and "s" are sin-type functions.

It appears that all the functionality is there to begin with, the relevant functions are
- The function [generate_transform](https://github.com/theochem/gbasis/blob/aa53bc1798d751f2f9e1f3909e6df4ffa704440b/gbasis/spherical.py#L229) converts from one Cartesian order to a specified Spherical order.
- The default Spherical order in gbasis is the same as PySCF and it is specified by [angmom_components_sph](https://github.com/theochem/gbasis/blob/aa53bc1798d751f2f9e1f3909e6df4ffa704440b/gbasis/contractions.py#L350) inside the class GeneralizedContractionShell. 
- When using iodata, you'll have to use the gbasis functoion [from_iodata](https://github.com/theochem/gbasis/blob/c57de8f1cfbe1dbaac8941c7cb9993797c76fca6/gbasis/wrappers.py#L6) which returns a list of [IODataShell](https://github.com/theochem/gbasis/blob/aa53bc1798d751f2f9e1f3909e6df4ffa704440b/gbasis/wrappers.py#L52), where the function `angmom_components_sph` is re-written to make it have IOData order.

**Is there a change to the code or algorithm you would like to see?**

Would like to change the API to better specify the order.  Couple of options come to mind:
- specifying the order when evaluating anything, e.g. evaluate_basis, electron_repulsion_integral. The downside of this, you'll have to change all functions that does evaluation/integrals.
- add an option to the constructor of the class GeneralizedContractionShell and wrappers like parse_nwchem, parse_gbs, from_iodata function that specifies common spherical order based on a string: .e.g "gbasis/PySCF", "iodata", "gaussian??", "Psi4?".  The downside is that it isn't general.
- add an option to the constructor of the class GeneralizedContractionShell and from_iodata function  where the user can specify their own  order by re-writting [angmom_components_sph](https://github.com/theochem/gbasis/blob/aa53bc1798d751f2f9e1f3909e6df4ffa704440b/gbasis/contractions.py#L350) function.  The downside is that it might be difficult for the user to specify their own order.

**Additional context**

- One can use IOdata "convert_convention_shell" to create a standard test.

**Comment by leila-pujal** [comment]
Hi @Ali-Tehrani, I was just reading this issue and got some questions about it; If I understood correctly your message you are requesting an API change to allow for the specification of custom spherical basis functions/Atomic orbitals ordering. 
My question would be if you could give an example of something you wanted to compute that requires this level of flexibility and that Gbasis how currently deals with the spherical order does not allow to do. I am asking this because based on the different options you proposed to fix this, I think they are all covered by the current code in Gbasis, which is basically IOData loading the file and dealing with the ordering, and if not from_pyscf or the parsers. You have worked with Gbasis so most likely I am missing something. Let me know what you think, I understand too this is an old issue and you may already solved it.

**Comment by PaulWAyers** [comment]
As @Ali-Tehrani points out, the functionality is there:
   https://github.com/theochem/gbasis/blob/e367156752681496cea2e72458ee7424c5058947/gbasis/contractions.py#L350
   https://github.com/theochem/gbasis/blob/e367156752681496cea2e72458ee7424c5058947/docs/notes.tex#L567

I'd support the API change to make this easier. I could imagine adding a convention as an optional argument for the functions (option 1 of Ali), but I could imagine that the optimal pathway is to support defining `angmom_components_sph` by either keyword or string. I am guessing that @Ali-Tehrani probably has the best idea of what's optimal.

**Comment by leila-pujal** [comment]
@PaulWAyers, I am becoming more familiar with Gbasis again, I apologize if there is something wrong in my following message. When I wrote my last message I was hoping @Ali-Tehrani to give a specific example because (I may be wrong on this since I've been looking at different codes lately) I think IOData does not impose a convention on the ordering of spherical harmonics. It stores the convention from the specific file format the wavefunction was loaded from. I tried to find a format where the ordering was different to get an example but so far all the ones I checked have the same ordering for spherical functions. The code I am referring to that loads the conventions is from IOData:
https://github.com/theochem/gbasis/blob/aa53bc1798d751f2f9e1f3909e6df4ffa704440b/gbasis/wrappers.py#L49

and

https://github.com/theochem/gbasis/blob/aa53bc1798d751f2f9e1f3909e6df4ffa704440b/gbasis/wrappers.py#L120

As I understand the functionality @Ali-Tehrani is asking for is already in place? At least for standard format files conventions. That's why I am a little confused and I thought if I saw an example I could understand better the request. Anyway let me know what you think about this and please let me know if there is something I am missing out. We can discuss this in today's meeting.

**Comment by Ali-Tehrani** [comment]
Hi @PaulWAyers and @leila-pujal, I had a talk with Leila today and I misunderstood and thought that GBasis works with a specific spherical ordering.  Leila is correct in that IOData reads the ordering specified by the input file and GBasis works with whatever conventions that is used.

The easiest solution she suggested would be to change the mol.obasis.conventions attribute inside the iodata object and feed that into the `from_iodata` within GBasis. Also I agree that this should be an IOData problem and not a Gbasis.
