### ISSUE TITLE
[REQUEST] Make lincint wrapper more flexible

### ISSUE THREAD

**Issue by FarnazH** [theochem/gbasis#178]
**Is there a change to the code or algorithm you would like to see?**
In the [libcint wrapper](https://github.com/theochem/gbasis/blob/master/gbasis/integrals/libcint.py):
- Add `notation` argument to allow for choosing between `"chemist"` and `"physics"` when computing `electron_repulsion_integral`.
- Add `transform` argument to all integral methods; make sure to keep arguments in the same order as original code. 

These two items can be addressed in separate PRs.

**Comment by msricher** [comment]
The first one is implemented and is in the code right now.

**Comment by leila-pujal** [comment]
Maybe I am totally mistaken because sometimes with the Libcint class some things slip, but for the `electron_repulsion` [here](https://github.com/theochem/gbasis/blob/8df478e7b842cd4b8965034f7039db5623c7e83b/gbasis/integrals/libcint.py#L1017) I was expecting and argument to pass what notation to choose so [here](https://github.com/theochem/gbasis/blob/8df478e7b842cd4b8965034f7039db5623c7e83b/gbasis/integrals/libcint.py#L826) it is choose based on what is passed. Maybe I am wrong and you can actually pass the argument already. If so, if you could add an example here that would be really helpful. Let me know what you think.

**Comment by FarnazH** [comment]
@msricher, I am confused too, and cannot take a closer look right now. You are right that the `notation` argument is supported, but it is not accessible when calling the [`electron_repulsion_integral`](https://github.com/theochem/gbasis/blob/8df478e7b842cd4b8965034f7039db5623c7e83b/gbasis/integrals/libcint.py#L1017) as @leila-pujal mentioned. 

Can you please give an example of how electron repulsion integrals can be computed with `"chemists"` notation?

**Comment by msricher** [comment]
Oh, that's right! I forgot to make the argument accessible with the user-facing functions. I will do that. Thank you both.

**Comment by leila-pujal** [comment]
No worries! Thanks a lot

**Comment by leila-pujal** [comment]
Do you think you can add this to PR #180 ?
