### ISSUE TITLE
Making a class structure

### ISSUE THREAD

**Issue by kimt33** [theochem/gbasis#32]
At the moment, with the exception of the data class `ContractedCartesianGaussians`, everything is a function. We're starting to see some duplication of the code especially for input check and linear combinations of constructed arrays. We have composite function calls to retrieves the appropriate array to manipulate. At the moment, we don't have enough features for this to be too unwieldy, but it will be nice to build a class structure that pieces everything together nicely.

I can think of two (not necessarily exclusive) structures that seem to make sense:
1. Each class is associated with a mathematical entity. We already have `ContractedCartesianGaussians` for the Cartesian contractions, but there are also spherical AO's, MO's, other linear combinations of orbitals, and even densities that are all manipulated to construct other structures. 
2. Each class is associated with the number of indices (associated with the Gaussian related object) needed to describe a given array. For example, the evaluations of the orbitals and their derivatives would be a one-index, and overlap of orbitals would be two-index. I guess in this sense, density and reduced density matrices would be zero-index. This lets us store develop a consistent API, for example for linearly transforming these indices.
3. Some combination of the two.

There are some questions that come to mind:
- Should the overlaps and other integrals computed via methods of the orbitals (contraction, AO, MO)?
- What about the evaluation of orbitals and their derivatives?
- Should the methods for producing these arrays be fed in orbitals instead?
- Which orbitals should be supported?
- Should the orbitals be represented with composite structure? i.e. need contractions to instantiate AO's, need AO's to instantiate MO's. 
- Should arrays be represented with composite structure? e.g. need orbital evaluations to instantiate density evaluations

Though I like the idea of having objects that I can manipulate just as I would on paper, I think that these classes will get quite unwieldy and we will end up with a Russian doll situation whenever we want to retrieve a piece of low level information (e.g. exponents). We can store the low-level information directly in the object, but instantiating the object will be less intuitive. Seeing as how different orbitals have the same structure (they're just linear combinations of one another), we will have repeated information and structure that will make things difficult to read. 

Of course, we can ignore these issues and simply say "we'll just make some porcelain (probably [iodata](https://github.com/theochem/iodata)) handle it" but the line between porcelain and plumbing is not too obvious if we expect our users to also be developers. If we want people to develop and contribute in a sustainable manner, we need to build a stable enough structure. Otherwise, we will need a gatekeeper to pore through each contribution. 

I think this is quite hard, especially since our goal is quite fuzzy. If I'm not mistaken, the current goal is to
- Make a python only code that is not too slow
- Have enough features for the release of [chemtools](https://github.com/theochem/iodata)
- Be extendible enough to facilitate future scientific works
- Be well tested and documented
- Be stable enough to not have an active maintainer 
which isn't easy to accomplish within a short time period. At the very least, this will require someone who's invested enough in accomplishing these goals to spend a good amount of time learning about the science, thinking about the code structure, and be willing to rip apart the entire structure a couple of times. Without this person, we will likely end up with a messy mixture that will make it even harder to refactor in the future.

For now (next few days?), I might create classes according to the number of indices with specific structures based on my whims.

**Comment by kimt33** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make classes for handling different kinds of manipulated Gaussian evaluations/integrations](https://trello.com/c/yk3SpYwg/48-make-classes-for-handling-different-kinds-of-manipulated-gaussian-evaluations-integrations)

**Comment by PaulWAyers** [comment]
It seems sensible. I'm not sure either and maybe @tovrstra or @FarnazH has some insight? My naive feeling is that I tend to like the "number of indices" structure just because it is how I think about it, it avoids (mostly?) Russian dolls, and it becomes obvious where extensions should be located. And my less-naive feeling is that I trust @kimt33 's ability to envision a nice framework.

To me, it is nice if somehow we have AOs as a keystone. AOs could be ContractedCartesianGaussians or their conversion to spherical, depending on the type of basis (Cartesian or Spherical). MOs are always linear combinations of AOs, and all other objects can be written as linear combinations of AOs (or indexed by AOs) at least. 

There is a sense in which I do not expect a lot of development here after it is finished. One might add a new type of integral/evaluation (which would, perforce, be 0-index, 1-index, 2-index, 3-index, or 4-index), and we have all but the 3-index already in the spec and the 3-index case that I can envision (density-fitting) is a tiny revision of 4-index case. @FarnazH has (or has been working on; I'm not sure the current status) an arbitrary-number-of-indices-Gaussian-overlap I guess we need to be sure we can play nicely with that, but I would not anticipate (m)any issues there.

The spec already has arbitrary-order derivatives; arbitrary-order moments; near-arbitrary interparticle evaluations, etc.. So the need for extensions is small. 

I'm not sure it informs this decision, but the only things I can imagine beyond what would be 0-to-4-index objects:
*  complex arguments/magnetic interactions/2-component relativity (spin becomes important)
*  higher-body terms (e.g., for nuclear physics), but that's sort of straightforward if tedious.
None of those are in the near-term plans I think, unless someone got very interested and then our maintainer issue is solved :-) . 

I'm really curious if others have ideas/feedback.

**Comment by kimt33** [comment]
See https://github.com/theochem/gbasis/blob/master/gbasis/contractions.py
